version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bolibro
      - DATABASE_DIRECT_URL=postgresql://postgres:postgres@db:5432/bolibro
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgis/postgis:14-3.3
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bolibro
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
