[phases.setup]
nixPkgs = ["nodejs", "nodejs.pkgs.typescript"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["ls -la", "ls -la prisma || mkdir -p prisma", "npx prisma generate --schema=./prisma/schema.prisma", "npm run build"]

[start]
cmd = "npm start" 