[variables]
NODE_ENV = "production"

[phases.setup]
aptPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "echo 'Current directory:'",
  "pwd",
  "echo 'Directory contents:'",
  "ls -la",
  "npm run build",
  "echo 'Build complete. Contents of dist:'",
  "ls -la dist || echo 'dist directory not found'",
  "echo 'Creating server.js in app root'",
  "cp index.js server.js"
]

[start]
cmd = "node server.js" 