[variables]
NODE_ENV = "production"

[phases.setup]
aptPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "echo 'Building server...'",
  "npm run build"
]

[start]
cmd = "node /app/server.js 2>/dev/null || node app-server.js 2>/dev/null || node server.js || node dist/index.js" 