[variables]
NODE_ENV = "production"

[phases.setup]
aptPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "echo 'Current directory:'",
  "pwd",
  "echo 'Directory contents:'",
  "ls -la",
  "npm run build",
  "echo 'Build complete. Contents of dist:'",
  "ls -la dist || echo 'dist directory not found'",
  "echo 'Ensuring server.js is in the correct location'",
  "cp server.js /app/server.js || echo 'Failed to copy server.js to /app'"
]

[start]
cmd = "node server.js" 