[variables]
NODE_ENV = "production"

[phases.setup]
aptPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "echo 'Building server...'",
  "npm run build",
  "echo 'Build output:'",
  "ls -la dist || echo 'dist directory not found or empty'"
]

[start]
cmd = "node server.js" 