[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node simple-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 