[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node bootstrap.js || node minimal-health.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_OPTIONS = "--max-old-space-size=512" 